### ISSUE TITLE
Stopped Working Since Recent Dev Branch

### ISSUE THREAD

**Issue by atericparker** [Vector35/Sidekick-public#8]
Around a week ago, Binja Dev & Sidekick updated and it hasn't worked since. Not sure if this is a python environment or plugin issue.

`[ScriptingProvider] Exception ignored on calling ctypes callback function: <bound method PythonScriptingProvider._load_module of <binaryninja.scriptingprovider.PythonScriptingProvider object at 0x7e888973b3e0>>
[ScriptingProvider] Traceback (most recent call last):
[ScriptingProvider]   File "/home/lain/binaryninja/plugins/../python/binaryninja/scriptingprovider.py", line 1092, in _load_module
[ScriptingProvider]     __import__(module)
[ScriptingProvider]   File "/home/lain/.binaryninja/repositories/official/plugins/Vector35_Sidekick/__init__.py", line 223, in <module>
[ScriptingProvider]     from .sidebars.suggestions_sidebar import SuggestionsSidebar, SUGGESTIONS_SIDEBAR_NAME
[ScriptingProvider]   File "/home/lain/.binaryninja/repositories/official/plugins/Vector35_Sidekick/sidebars/suggestions_sidebar.py", line 16, in <module>
[ScriptingProvider]     from ..suggestions.assistant import DecompilerAssistant
[ScriptingProvider]   File "/home/lain/.binaryninja/repositories/official/plugins/Vector35_Sidekick/suggestions/assistant.py", line 14, in <module>
[ScriptingProvider]     from .suggestion_classes import (
[ScriptingProvider]   File "/home/lain/.binaryninja/repositories/official/plugins/Vector35_Sidekick/suggestions/suggestion_classes.py", line 18, in <module>
[ScriptingProvider]     from ..background_tasks.name_functions import NameAllFunctionsTask
[ScriptingProvider]   File "/home/lain/.binaryninja/repositories/official/plugins/Vector35_Sidekick/background_tasks/name_functions.py", line 9, in <module>
[ScriptingProvider]     from ..sidekick_api_client import SidekickAPIClient, SidekickAPIError
[ScriptingProvider]   File "/home/lain/.binaryninja/repositories/official/plugins/Vector35_Sidekick/sidekick_api_client.py", line 19, in <module>
[ScriptingProvider]     from networkx.readwrite.json_graph.node_link import node_link_data
[ScriptingProvider]   File "/home/lain/.binaryninja/python312/site-packages/networkx/__init__.py", line 23, in <module>
[ScriptingProvider]     config = utils.backends._set_configs_from_environment()
[ScriptingProvider]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ScriptingProvider]   File "/home/lain/.binaryninja/python312/site-packages/networkx/utils/backends.py", line 574, in _set_configs_from_environment
[ScriptingProvider]     backends=Config(
[ScriptingProvider]              ^^^^^^^
[ScriptingProvider]   File "/home/lain/.binaryninja/python312/site-packages/networkx/utils/configs.py", line 84, in __new__
[ScriptingProvider]     cls = dataclass(
[ScriptingProvider]           ^^^^^^^^^^
[ScriptingProvider]   File "/usr/lib/python3.12/dataclasses.py", line 1265, in wrap
[ScriptingProvider]     return _process_class(cls, init, repr, eq, order, unsafe_hash,
[ScriptingProvider]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ScriptingProvider]   File "/usr/lib/python3.12/dataclasses.py", line 1063, in _process_class
[ScriptingProvider]     _init_fn(all_init_fields,
[ScriptingProvider]   File "/usr/lib/python3.12/dataclasses.py", line 619, in _init_fn
[ScriptingProvider]     return _create_fn('__init__',
[ScriptingProvider]            ^^^^^^^^^^^^^^^^^^^^^^
[ScriptingProvider]   File "/usr/lib/python3.12/dataclasses.py", line 473, in _create_fn
[ScriptingProvider]     exec(txt, globals, ns)
[ScriptingProvider] SyntaxError: invalid syntax (<string>, line 1)
`

**Comment by r0ny123** [comment]
I faced the Same error. It happened to me too. cc @psifertex
```
[Default] Exception ignored on calling ctypes callback function: <bound method PythonScriptingProvider._load_module of <binaryninja.scriptingprovider.PythonScriptingProvider object at 0x0000022729528670>>
[Default] Traceback (most recent call last):
[Default]   File "C:\Users\Rony\AppData\Local\Vector35\BinaryNinja\plugins\..\python\binaryninja\scriptingprovider.py", line 1090, in _load_module
[Default]     __import__(module)
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_Sidekick\__init__.py", line 223, in <module>
[Default]     from .sidebars.suggestions_sidebar import SuggestionsSidebar, SUGGESTIONS_SIDEBAR_NAME
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_Sidekick\sidebars\suggestions_sidebar.py", line 16, in <module>
[Default]     from ..suggestions.assistant import DecompilerAssistant
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_Sidekick\suggestions\assistant.py", line 14, in <module>
[Default]     from .suggestion_classes import (
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_Sidekick\suggestions\suggestion_classes.py", line 18, in <module>
[Default]     from ..background_tasks.name_functions import NameAllFunctionsTask
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_Sidekick\background_tasks\name_functions.py", line 9, in <module>
[Default]     from ..sidekick_api_client import SidekickAPIClient, SidekickAPIError
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\repositories\official\plugins\Vector35_Sidekick\sidekick_api_client.py", line 19, in <module>
[Default]     from networkx.readwrite.json_graph.node_link import node_link_data
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\python310\site-packages\networkx\__init__.py", line 23, in <module>
[Default]     config = utils.backends._set_configs_from_environment()
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\python310\site-packages\networkx\utils\backends.py", line 574, in _set_configs_from_environment
[Default]     backends=Config(
[Default]   File "C:\Users\Rony\AppData\Roaming\Binary Ninja\python310\site-packages\networkx\utils\configs.py", line 84, in __new__
[Default]     cls = dataclass(
[Default]   File "dataclasses.py", line 1175, in wrap
[Default]   File "dataclasses.py", line 1024, in _process_class
[Default]   File "dataclasses.py", line 579, in _init_fn
[Default]   File "dataclasses.py", line 432, in _create_fn
[Default] SyntaxError: invalid syntax (<string>, line 1)
```

**Comment by psifertex** [comment]
I believe this is solved by https://docs.sidekick.binary.ninja/issues/ski-2/

**Comment by psifertex** [comment]
Sadly, we're currently limited to the whims of pip for dependency management which is... problematic at best.
